permissions: write-all

name: 5-[destroy].yml
on:
  push:
    branches:
      - 'release/destroy-**'
env:
    ECR_REPO: ${{ vars.ECR_REPO }}

jobs:
  releaseDestroy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "sa-east-1"
      AWS_S3_BUCKET: "recipe-app-api-devops-tfstate-juliazuin2"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3     

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
    
      - name: Terraform set workspace
        run: terraform workspace select release 
    
      - name: Terraform destroy
        run: terraform destroy --auto-approve
        env:
          TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}          
          TF_VAR_django_secret_key: ${{ secrets.TF_VAR_django_secret_key }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
